export const HousesData = [
    {
        id:0,
        type: "house",
        price: "100000",
        location: "makeni",
        image: "https://images.pexels.com/photos/323776/pexels-photo-323776.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
    {
        id:1,
        type: "apartment",
        price: "100000",
        location: "silver rest",
        image: "https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
    {
        id:2,
        type: "apartment",
        price: "8000",
        location: "kabwata",
        image: "https://images.pexels.com/photos/53610/large-home-residential-house-architecture-53610.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
    {
        id:3,
        type: "house",
        price: "100000",
        location: "kabwata",
        image: "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
    {
        id:4,
        type: "house",
        price: "870",
        location: "high bex hills",
        image: "https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
    {
        id:5,
        type: "apartment",
        price: "90",
        location: "phi",
        image: "https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
    {
        id:6,
        type: "hotel",
        price: "100",
        location: "new kasama",
        image: "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
    {
        id:7,
        type: "hotel",
        price: "900",
        location: "shatumbo",
        image: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
    {
        id:8,
        type: "lodge",
        price: "900",
        location: "shatumbo",
        image: "https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
    {
        id:9,
        type: "estate",
        price: "900",
        location: "chongwe",
        image: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=600",
        title: "Mountain hills",
    },
]