export const HousesData = [
    {
        id:0,
        type: "house",
        price: "100000",
        location: "makeni",
        image: "/imgs/pexels-alex-staudinger-1732414.jpg",
        title: "Mountain hills",
    },
    {
        id:1,
        type: "apartment",
        price: "100000",
        location: "silver rest",
        image: "imgs/pexels-binyamin-mellish-106399.jpg",
        title: "Mountain hills",
    },
    {
        id:2,
        type: "apartment",
        price: "8000",
        location: "kabwata",
        image: "imgs/pexels-binyamin-mellish-1396132.jpg",
        title: "Mountain hills",
    },
    {
        id:3,
        type: "house",
        price: "100000",
        location: "kabwata",
        image: "/imgs/pexels-curtis-adams-3935333.jpg",
        title: "Mountain hills",
    },
    {
        id:4,
        type: "house",
        price: "870",
        location: "high bex hills",
        image: "imgs/pexels-expect-best-323780.jpg",
        title: "Mountain hills",
    },
    {
        id:5,
        type: "apartment",
        price: "90",
        location: "phi",
        image: "imgs/pexels-eziz-charyyev-1475938.jpg",
        title: "Mountain hills",
    },
    {
        id:6,
        type: "hotel",
        price: "100",
        location: "new kasama",
        image: "imgs/pexels-luis-yanez-206172.jpg",
        title: "Mountain hills",
    },
    {
        id:7,
        type: "hotel",
        price: "900",
        location: "shatumbo",
        image: "imgs/pexels-expect-best-323776.jpg",
        title: "Mountain hills",
    },
    {
        id:8,
        type: "lodge",
        price: "900",
        location: "shatumbo",
        image: "imgs/pexels-expect-best-323775.jpg",
        title: "Mountain hills",
    },
    {
        id:9,
        type: "estate",
        price: "900",
        location: "chongwe",
        image: "imgs/pexels-photomix-company-565324.jpg",
        title: "Mountain hills",
    },
]